package com.example.craftmaster;

import java.util.ArrayList;
import java.util.List;

public class CraftGenerator {

	public static List<Craft> generateCrafts() {
		List<Craft> crafts = new ArrayList<Craft>();

		crafts.add(new Craft(100, "Grundstück"));
		crafts.add(new Craft(110, "Grundstückswert"));
		crafts.add(new Craft(120, "Grundstücksnebenkosten"));
		crafts.add(new Craft(130, "Freimachen"));
		crafts.add(new Craft(200, "Herrichten und Erschließen"));
		crafts.add(new Craft(210, "Herrichten"));
		crafts.add(new Craft(211, "Sicherungsmaßnahmen"));
		crafts.add(new Craft(212, "Abbruchmaßnahmen"));
		crafts.add(new Craft(213, "Altlastenbeseitigung"));
		crafts.add(new Craft(214, "Herrichten der Geländeoberfläche"));
		crafts.add(new Craft(219, "Herrichten, Sonstiges"));
		crafts.add(new Craft(220, "Öffentliche Erschließung"));
		crafts.add(new Craft(221, "Abwasserentsorgung"));
		crafts.add(new Craft(222, "Wasserversorgung"));
		crafts.add(new Craft(223, "Gasversorgung"));
		crafts.add(new Craft(224, "Fernwärmeversorgung"));
		crafts.add(new Craft(225, "Stromversorgung"));
		crafts.add(new Craft(226, "Telekommunikation"));
		crafts.add(new Craft(227, "Verkehrserschließung"));
		crafts.add(new Craft(229, "Öffentliche Erschließung, Sonstiges"));
		crafts.add(new Craft(230, "Nichtöffentliche Erschließung"));
		crafts.add(new Craft(240, "Ausgleichsabgaben"));
		crafts.add(new Craft(300, "Bauwerk - Baukonstruktionen"));
		crafts.add(new Craft(310, "Baugrube"));
		crafts.add(new Craft(311, "Baugrubenherstellung"));
		crafts.add(new Craft(312, "Baugrubenerschließung"));
		crafts.add(new Craft(313, "Wasserhaltung"));
		crafts.add(new Craft(319, "Baugrube, Sonstiges"));
		crafts.add(new Craft(320, "Gründung"));
		crafts.add(new Craft(321, "Baugrundverbesserung"));
		crafts.add(new Craft(322, "Flachgründungen"));
		crafts.add(new Craft(323, "Tiefgründungen"));
		crafts.add(new Craft(324, "Unterböden und Bodenplatten"));
		crafts.add(new Craft(325, "Bodenbeläge"));
		crafts.add(new Craft(326, "Bauwerksabdichtungen"));
		crafts.add(new Craft(327, "Drainagen"));
		crafts.add(new Craft(329, "Gründungen, Sonstiges"));
		crafts.add(new Craft(330, "Außenwände"));
		crafts.add(new Craft(331, "Tragende Außenwände"));
		crafts.add(new Craft(332, "Nichttragende Außenwände"));
		crafts.add(new Craft(333, "Außenstützen"));
		crafts.add(new Craft(334, "Außentüren und -fenster"));
		crafts.add(new Craft(335, "Außenwandbekleidungen außen"));
		crafts.add(new Craft(336, "Außenwandbekleidungen innen"));
		crafts.add(new Craft(337, "Elementierte Außenwände"));
		crafts.add(new Craft(338, "Sonnenschutz"));
		crafts.add(new Craft(339, "Außenwände, Sonstiges"));
		crafts.add(new Craft(340, "Innenwände"));
		crafts.add(new Craft(341, "Tragende Innenwände"));
		crafts.add(new Craft(342, "Nichttragende Innenwände"));
		crafts.add(new Craft(343, "Innenstützen"));
		crafts.add(new Craft(344, "Innentüren und -fenster"));
		crafts.add(new Craft(345, "Innenwandbekleidungen"));
		crafts.add(new Craft(346, "Elementierte Innenwände"));
		crafts.add(new Craft(349, "Innwände, Sonstiges"));
		crafts.add(new Craft(350, "Decken"));
		crafts.add(new Craft(351, "Deckenkonstruktion"));
		crafts.add(new Craft(352, "Deckenbeläge"));
		crafts.add(new Craft(353, "Deckenbekleidungen"));
		crafts.add(new Craft(359, "Decken, Sonstiges"));
		crafts.add(new Craft(360, "Dächer"));
		crafts.add(new Craft(361, "Dachkonstruktionen"));
		crafts.add(new Craft(362, "Dachfenster, Dachöffnungen"));
		crafts.add(new Craft(363, "Dachbeläge"));
		crafts.add(new Craft(364, "Dachbekleidungen"));
		crafts.add(new Craft(369, "Dächer, Sonstiges"));
		crafts.add(new Craft(370, "Baukonstruktive Einbauten"));
		crafts.add(new Craft(370, "Baukonstruktive Einbauten"));
		crafts.add(new Craft(371, "Allgemeine Einbauten"));
		crafts.add(new Craft(371, "Allgemeine Einbauten"));
		crafts.add(new Craft(372, "Besondere Einbauten"));
		crafts.add(new Craft(372, "Besondere Einbauten"));
		crafts.add(new Craft(379, "Baukonstruktive Einbauten, Sonstige"));
		crafts.add(new Craft(379, "Baukonstruktive Einbauten, Sonstiges"));
		crafts.add(new Craft(380, "Grundkonstruktionen"));
		crafts.add(new Craft(38002, "Erdarbeiten"));
		crafts.add(new Craft(38006, "Verbau-, Ramm- und Einpressarbeiten"));
		crafts.add(new Craft(38008, "Wasserhaltungarbeiten"));
		crafts.add(new Craft(38010, "Drainarbeiten"));
		crafts.add(new Craft(38012, "Mauerarbeiten"));
		crafts.add(new Craft(38013, "Beton- und Stahlbetonarbeiten"));
		crafts.add(new Craft(38014, "Naturwerkstein., Betonwerksteinarbeiten"));
		crafts.add(new Craft(38016, "Zimmer- und Holzbauarbeiten"));
		crafts.add(new Craft(38017, "Stahlbauarbeiten"));
		crafts.add(new Craft(38018, "Abdichtungsarbeiten gegen Wasser"));
		crafts.add(new Craft(38020, "Dachdeckungsarbeiten"));
		crafts.add(new Craft(38021, "Dachdichtungsarbeiten"));
		crafts.add(new Craft(38022, "Klempnerarbeiten"));
		crafts.add(new Craft(38023, "Putz- und Stuckarbeiten"));
		crafts.add(new Craft(38024, "Fliesen- und Plattenarbeiten"));
		crafts.add(new Craft(38025, "Estricharbeiten"));
		crafts.add(new Craft(38027, "Tischlerarbeiten"));
		crafts.add(new Craft(38028, "Parkettarbeiten und Holzpflasterarbeiten"));
		crafts.add(new Craft(38029, "Beschlagarbeiten"));
		crafts.add(new Craft(38030,
				"Rollladenarbeiten, Rollabschlüsse, Sonnenschutz- und Verdunklungsanlagen"));
		crafts.add(new Craft(38031, "Metallbauarbeiten und Schlosserarbeiten"));
		crafts.add(new Craft(38032, "Verglasungsarbeiten"));
		crafts.add(new Craft(38034, "Maler- und Lackierungsarbeiten"));
		crafts.add(new Craft(38035,
				"Korrosionsschutzarbeiten, Stahl- und Aluminiumbaukontruktionen"));
		crafts.add(new Craft(38036, "Bodenbelagsarbeiten"));
		crafts.add(new Craft(38037, "Tapezierarbeiten"));
		crafts.add(new Craft(38039, "Trockenbauarbeiten"));
		crafts.add(new Craft(390, "Sonstige Maßnahmen für Baukontruktionen"));
		crafts.add(new Craft(391, "Baustelleneinrichtung"));
		crafts.add(new Craft(392, "Gerüste"));
		crafts.add(new Craft(393, "Sicherungsmaßnahmen"));
		crafts.add(new Craft(394, "Abbruchmaßnahmen"));
		crafts.add(new Craft(395, "Instandsetzungen"));
		crafts.add(new Craft(396, "Recycling, Zwischendeponien, Entsorgung"));
		crafts.add(new Craft(397, "Schlechtwetterbau"));
		crafts.add(new Craft(398, "Zusätzliche Maßnahmen"));
		crafts.add(new Craft(399,
				"Sonstige Maßnahmen für Baukontruktionen, Sonstiges"));
		crafts.add(new Craft(400, "Bauwerk - Technische Anlagen"));
		crafts.add(new Craft(410, "Abwasser-, Wasser-, Gasanlagen"));
		crafts.add(new Craft(411, "Abwasseranlagen"));
		crafts.add(new Craft(412, "Wasseranlagen"));
		crafts.add(new Craft(413, "Gasanlagen"));
		crafts.add(new Craft(414, "Feuerlöschanlagen"));
		crafts.add(new Craft(419, "Abwasser-, Wasser-, Gasanlagen, Sonstiges"));
		crafts.add(new Craft(420, "Wärmeversorgungsanlagen"));
		crafts.add(new Craft(421, "Wärmeerzeugungsanlagen"));
		crafts.add(new Craft(422, "Wärmeverteilnetze"));
		crafts.add(new Craft(423, "Raumheizflächen"));
		crafts.add(new Craft(429, "Wärmeversorgungsanlagen, Sonstiges"));
		crafts.add(new Craft(430, "Lufttechnische Anlagen"));
		crafts.add(new Craft(431, "Lüftungsanlagen"));
		crafts.add(new Craft(432, "Teilklimaanlagen"));
		crafts.add(new Craft(433, "Klimaanlagen"));
		crafts.add(new Craft(434, "Prozesslufttechnische Anlagen"));
		crafts.add(new Craft(435, "Kälteanlagen"));
		crafts.add(new Craft(439, "Lufttechnische Anlagen, Sonstige"));
		crafts.add(new Craft(440, "Starkstromanlagen"));
		crafts.add(new Craft(441, "Hoch- und Mittelspannungsanlagen"));
		crafts.add(new Craft(442, "Eigenstromversorgungsanlagen"));
		crafts.add(new Craft(443, "Niederspannungsschaltanlagen"));
		crafts.add(new Craft(444, "Niederspannungsinstallationsanlagen"));
		crafts.add(new Craft(445, "Beleuchtungsanlagen"));
		crafts.add(new Craft(446, "Blitzschutz- und Erdungsanlagen"));
		crafts.add(new Craft(449, "Starkstromanlagen, Sonstiges"));
		crafts.add(new Craft(450,
				"Fernmelde- und informationstechnische Anlagen"));
		crafts.add(new Craft(451, "Telekommunikationsanlagen"));
		crafts.add(new Craft(452, "Such- und Signalanlagen"));
		crafts.add(new Craft(453, "Zeitdienstanlagen"));
		crafts.add(new Craft(454, "Elektroakustische Anlagen"));
		crafts.add(new Craft(455, "Fernseh- und Antennenanlagen"));
		crafts.add(new Craft(456, "Gefahrmelde- und Alarmanlagen"));
		crafts.add(new Craft(457, "Übertragungsnetze"));
		crafts.add(new Craft(459,
				"Fernmelde- und informationstechnische Anlagen, Sonstiges"));
		crafts.add(new Craft(460, "Förderanlagen"));
		crafts.add(new Craft(461, "Aufzugsanlagen"));
		crafts.add(new Craft(462, "Fahrtreppen, Fahrsteige"));
		crafts.add(new Craft(463, "Befahranlagen"));
		crafts.add(new Craft(464, "Transportanlagen"));
		crafts.add(new Craft(465, "Krananlagen"));
		crafts.add(new Craft(469, "Förderanlagen, Sonstiges"));
		crafts.add(new Craft(470, "Nutzungsspezifische Anlagen"));
		crafts.add(new Craft(471, "Küchentechnische Anlagen"));
		crafts.add(new Craft(472, "Wäscherei- und Reinigungsanlagen"));
		crafts.add(new Craft(473, "Medienversorgungsanlagen"));
		crafts.add(new Craft(474, "Medizintechnische Anlagen"));
		crafts.add(new Craft(475, "Labortechnische Anlagen"));
		crafts.add(new Craft(476, "Badetechnische Anlagen"));
		crafts.add(new Craft(477, "Kälteanlagen"));
		crafts.add(new Craft(478, "Entsorgungsanlagen"));
		crafts.add(new Craft(479, "Nutzungsspezifische Anlagen, Sonstiges"));
		crafts.add(new Craft(480, "Gebäudeautomation"));
		crafts.add(new Craft(481, "Automationssysteme"));
		crafts.add(new Craft(482, "Leistungsteile"));
		crafts.add(new Craft(483, "Zentrale Einrichtungen"));
		crafts.add(new Craft(489, "Gebäudeautomation, Sonstiges"));
		crafts.add(new Craft(490, "Sonstige Maßnahmen für technische Anlagen"));
		crafts.add(new Craft(491, "Baustelleneinrichtung"));
		crafts.add(new Craft(492, "Gerüste"));
		crafts.add(new Craft(493, "Sicherungsmaßnahmen"));
		crafts.add(new Craft(494, "Abbruchmaßnahmen"));
		crafts.add(new Craft(495, "Instandsetzungen"));
		crafts.add(new Craft(496, "Recycling, Zwischendeponien, Entsorgung"));
		crafts.add(new Craft(497, "Schlechtwetterbau"));
		crafts.add(new Craft(498, "Zusätzliche Maßnahmen"));
		crafts.add(new Craft(499,
				"Sonstige Maßnahmen für technische Anlagen, Sonstiges"));
		crafts.add(new Craft(500, "Außenanlagen"));
		crafts.add(new Craft(510, "Geländeflächen"));
		crafts.add(new Craft(511, "Geländebearbeitung"));
		crafts.add(new Craft(512, "Vegetationstechnische Bodenbearbeitung"));
		crafts.add(new Craft(513, "Sicherungsbauweisen"));
		crafts.add(new Craft(514, "Pflanzen"));
		crafts.add(new Craft(515, "Rasen"));
		crafts.add(new Craft(516, "Begrünung unterbauter Flächen"));
		crafts.add(new Craft(517, "Wasserflächen"));
		crafts.add(new Craft(519, "Geländeflächen, Sonstiges"));
		crafts.add(new Craft(520, "Befestigte Flächen"));
		crafts.add(new Craft(521, "Wege"));
		crafts.add(new Craft(522, "Straßen"));
		crafts.add(new Craft(523, "Plätze, Höfe"));
		crafts.add(new Craft(524, "Stellplätze"));
		crafts.add(new Craft(525, "Sportplatzflächen"));
		crafts.add(new Craft(526, "Spielplatzflächen"));
		crafts.add(new Craft(527, "Gleisanlagen"));
		crafts.add(new Craft(529, "Befestigte Flächen, Sonstiges"));
		crafts.add(new Craft(530, "Baukonstruktionen in Außenanlagen"));
		crafts.add(new Craft(531, "Einfriedungen"));
		crafts.add(new Craft(532, "Schutzkotruktionen"));
		crafts.add(new Craft(533, "Mauern, Wände"));
		crafts.add(new Craft(534, "Rampen, Treppen, Tribünen"));
		crafts.add(new Craft(535, "Überdachungen"));
		crafts.add(new Craft(536, "Brücken, Stege"));
		crafts.add(new Craft(537, "Kanal- und Schachtbauarbeiten"));
		crafts.add(new Craft(538, "Wasserbauliche Anlagen"));
		crafts.add(new Craft(539,
				"Baukonstruktionen in Außenanlagen, Sonstiges"));
		crafts.add(new Craft(540, "Technische Anlagen im Außenanlagen"));
		crafts.add(new Craft(541, "Abwasseranlagen"));
		crafts.add(new Craft(542, "Wasseranlagen"));
		crafts.add(new Craft(543, "Gasanlagen"));
		crafts.add(new Craft(544, "Wärmevesorgungsanlagen"));
		crafts.add(new Craft(545, "Lufttechnische Anlagen"));
		crafts.add(new Craft(546, "Starkstromanlagen"));
		crafts.add(new Craft(547,
				"Fernmelde- und informationstechnische Anlagen"));
		crafts.add(new Craft(548, "Nutzungsspezifische Anlagen"));
		crafts.add(new Craft(549,
				"Technische Anlagen in Außenanlagen, Sonstiges"));
		crafts.add(new Craft(550, "Einbauten in Außenanlagen"));
		crafts.add(new Craft(551, "Allgemeine Einbauten"));
		crafts.add(new Craft(552, "Besondere Einbauten"));
		crafts.add(new Craft(559, "Einbauten in Außenanlagen, Sonstige"));
		crafts.add(new Craft(590, "Sonstige Maßnahmen für Außenanlagen"));
		crafts.add(new Craft(591, "Baustelleneinrichtung"));
		crafts.add(new Craft(592, "Gerüste"));
		crafts.add(new Craft(593, "Sicherungsmaßnahmen"));
		crafts.add(new Craft(594, "Abbruchmaßnahmen"));
		crafts.add(new Craft(595, "Instandsetzungen"));
		crafts.add(new Craft(596, "Recycling, Zwischendeponien und Entsorgung"));
		crafts.add(new Craft(597, "Shlechtwetterbau"));
		crafts.add(new Craft(598, "Zusätzliche Maßnahmen"));
		crafts.add(new Craft(599,
				"Sonstige Maßnahmen für Außenanlagen, Sonstiges"));
		crafts.add(new Craft(600, "Ausstattung und Kunstwerke"));
		crafts.add(new Craft(610, "Ausstattung"));
		crafts.add(new Craft(611, "Allgemeine Ausrüstung"));
		crafts.add(new Craft(612, "Besondere Ausrüstung"));
		crafts.add(new Craft(619, "Ausstattung, Sonstiges"));
		crafts.add(new Craft(620, "Kunstwerke"));
		crafts.add(new Craft(621, "Kunstobjekte"));
		crafts.add(new Craft(622,
				"Künstlerisch gestaltete Bauteile und Bauwerke"));
		crafts.add(new Craft(623,
				"Künstlerisch gestaltete Bauteile und Außenanlagen"));
		crafts.add(new Craft(629, "Kunstwerke, Sonstiges"));
		crafts.add(new Craft(700, "Baunebenkosten"));
		crafts.add(new Craft(710, "Bauherrenaufgaben"));
		crafts.add(new Craft(711, "Projektleitung"));
		crafts.add(new Craft(712, "Projektsteuerung"));
		crafts.add(new Craft(713, "Betriebs- und Organisationsberatung"));
		crafts.add(new Craft(719, "Bauherrenaufgaben, Sonstiges"));
		crafts.add(new Craft(720, "Vorbereitung der Objektplanung"));
		crafts.add(new Craft(721, "Untersuchungen"));
		crafts.add(new Craft(722, "Wertermittlung"));
		crafts.add(new Craft(723, "Städtebaulichen Leistungen"));
		crafts.add(new Craft(724, "Landschaftsplanerische Leistungen"));
		crafts.add(new Craft(725, "Wettbewerbe"));
		crafts.add(new Craft(729, "Vorbereitung der Objektplanung, Sonstiges"));
		crafts.add(new Craft(730, "Architekten- und Ingenieurleistungen"));
		crafts.add(new Craft(731, "Gebäude"));
		crafts.add(new Craft(732, "Freianlagen"));
		crafts.add(new Craft(733, "Raumbildende Ausbauten"));
		crafts.add(new Craft(734, "Ingenieurbauwerke und Verkehrsanlagen"));
		crafts.add(new Craft(735, "Tragwerksplanung"));
		crafts.add(new Craft(736, "Technische Ausrüstung"));
		crafts.add(new Craft(739,
				"Architekten- und Ingenieurleistungen, Sonstiges"));
		crafts.add(new Craft(740, "Gutachten und Beratung"));
		crafts.add(new Craft(741, "Thermische Bauphysik"));
		crafts.add(new Craft(742, "Schallschutz und Raumakustik"));
		crafts.add(new Craft(743, "Bodenmechanik, Erd- und Grundbau"));
		crafts.add(new Craft(744, "Vermessung"));
		crafts.add(new Craft(745, "Lichttechnik, Tageslichttechnik"));
		crafts.add(new Craft(749, "Gutachten und Beratung, Sonstiges"));
		crafts.add(new Craft(750, "Kunst"));
		crafts.add(new Craft(751, "Kunstwettbewerbe"));
		crafts.add(new Craft(752, "Honorare"));
		crafts.add(new Craft(759, "Kunst, Sonstiges"));
		crafts.add(new Craft(770, "Allgemeine Baunebenkosten"));
		crafts.add(new Craft(771, "Prüfungen, Genehmigungen"));
		crafts.add(new Craft(772, "Bewirtschaftungskosten"));
		crafts.add(new Craft(773, "Bemusterungskosten"));
		crafts.add(new Craft(774, "Betriebskosten während der Bauzeit"));
		crafts.add(new Craft(779, "Allgemeine Baunebenkosten, Sonstiges"));
		crafts.add(new Craft(790, "Sonstige Baunebenkosten"));

		return crafts;

	}

}
